# $schema: ../vendor/symfony/routing/Loader/schema/routing.schema.json

controllers:
    resource: attributes
    type: tagged_services


api_refresh_token:
    path: /api/token/refresh


api_controller_v1:
    resource: "routes/v1.yaml"
    #    type: attribute
    prefix: /api
#    defaults:
#        _locale: '%locale%'
